name: OP
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py37_0
  - backcall=0.1.0=py37_0
  - beautifulsoup4=4.8.2=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - conda=4.8.2=py37_0
  - conda-build=3.18.11=py37_0
  - conda-package-handling=1.6.0=py37h7b6447c_0
  - cryptography=2.8=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - cython=0.29.14=py37he6710b0_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - expat=2.2.6=he6710b0_0
  - filelock=3.0.12=py_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - glob2=0.7=py_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - intel-openmp=2019.4=243
  - ipython=7.10.2=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.16.0=py37_0
  - jinja2=2.11.1=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - libarchive=3.3.3=h5d8350f_5
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblief=0.9.0=h7725739_2
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_4
  - pandas=0.25.3=py37he6710b0_0
  - parso=0.6.0=py_0
  - patchelf=0.10=he6710b0_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.0.2=py37_0
  - pkginfo=1.5.0.1=py37_0
  - prompt_toolkit=3.0.2=py_0
  - protobuf=3.11.2=py37he6710b0_0
  - psutil=5.6.7=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - py-lief=0.9.0=py37h7725739_2
  - pycocotools=2.0.0=py37h516909a_1000
  - pycosat=0.6.3=py37h7b6447c_0
  - pycparser=2.19=py37_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_0
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python-libarchive-c=2.8=py37_13
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - pyyaml=5.2=py37h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_1
  - ripgrep=11.0.2=he32d670_0
  - ruamel_yaml=0.15.87=py37h7b6447c_0
  - scipy=1.3.2=py37h7c811a0_0
  - seaborn=0.10.0=py_0
  - setuptools=45.1.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - soupsieve=1.9.5=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py37_cu101
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.40.0=py_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - future==0.18.2
    - opencv-python==3.4.8.29

